name: Banashri notes
highlighter: rouge
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

relative_links:
  enabled:     true
  collections: false

paginate: 2
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-relative-links]
